services:
  web:
    build: .
    image: eduardovilla.com
    container_name: eduardovilla-web
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - SITE_URL=https://eduardovilla.com
